{% set name = "kazoo" %}
{% set version = "2.6.0" %}
{% set sha256 = "af2a416c7c79f58403dfc010bf84c4a514ef00c9b61a3e03a508146f3c1ea553" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - setuptools
    - pip
  host:
    - pip
  run:
    - python
    - six

test:
  imports:
    - kazoo

about:
  home: http://github.com/python-zk/kazoo
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Kazoo is a high-level Python library that makes it easier to use Apache Zookeeper'

  description: Kazoo is a high-level Python library that makes it easier to use Apache Zookeeper
  doc_url: https://kazoo.readthedocs.io/
  dev_url: https://github.com/python-zk/kazoo

extra:
  recipe-maintainers:
      - mrocklin
      - emmett9001
