{% set name = "kazoo" %}
{% set version = "2.5.0" %}
{% set sha256 = "8db774f7bdece7d0dc7decb21539ff0852e42c2ffe1c28d7f1ff6f9292a1c3a4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - kazoo

about:
  home: http://github.com/python-zk/kazoo
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Kazoo is a high-level Python library that makes it easier to use Apache Zookeeper'

  description: Kazoo is a high-level Python library that makes it easier to use Apache Zookeeper
  doc_url: https://kazoo.readthedocs.io/
  dev_url: https://github.com/python-zk/kazoo

extra:
  recipe-maintainers:
      - mrocklin
      - emmett9001
